/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shhua8751
 */

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JFrame;
        
public class FormKolofon extends javax.swing.JFrame {
    //ArrayList    <ArrayList<String>>   athlete      =   new   ArrayList<ArrayList<String>>();
    //ArrayList    <String>   name         =   new   ArrayList(athlete.subList(0, athlete.size()));
    ArrayList    <String>   firstName    =   new   ArrayList();
    ArrayList    <String>   lastName     =   new   ArrayList();
    ArrayList    <String>   gender       =   new   ArrayList();
    ArrayList    <String>   birthDate    =   new   ArrayList();
    ArrayList    <String>   nationality  =   new   ArrayList();
    
    
    //Athlete num arraylists
    ArrayList    <String>   athleteOne   =   new   ArrayList();
    ArrayList    <String>   athleteTwo   =   new   ArrayList();
    
    
    //Transfer need components
       String name;
       String genders;
       String Dob;
       String country;
       
     //For pop up
       String f1;
       String l2;
       String g3;
       String b4;
       String n5;
       
       //format
       SimpleDateFormat s = new SimpleDateFormat ("MMM-dd-yyyy");
       
   
    /**
     * Creates new form FormKolofon2
     */
    public FormKolofon() {
        initComponents();
        resetButton.setEnabled(false);
        createButton.setEnabled(false);
        profileLabel.setVisible(false);
        
        disableLabel();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        failPane = new javax.swing.JOptionPane();
        successPane = new javax.swing.JOptionPane();
        kolofonLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JRadioButton();
        firstLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        birthLabel = new javax.swing.JLabel();
        firstInput = new javax.swing.JTextField();
        lastInput = new javax.swing.JTextField();
        genderBox = new javax.swing.JComboBox();
        createButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        nationLabel = new javax.swing.JLabel();
        nationBox = new javax.swing.JComboBox();
        profileLabel = new javax.swing.JLabel();
        birthInput = new javax.swing.JFormattedTextField();
        formatLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kolofonLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        kolofonLabel.setText("Kolofon");

        newButton.setText("New Athelete");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Registerd Athlete");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        firstLabel.setText("First Name:");

        lastLabel.setText("Last Name:");

        genderLabel.setText("Gender:");

        birthLabel.setText("Date of Birth:");

        lastInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastInputActionPerformed(evt);
            }
        });

        genderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Gender", "Male", "Female" }));
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        nationLabel.setText("Nationality:");

        nationBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Nationality", "Canada", "PR Of China" }));

        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });

        birthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthInputActionPerformed(evt);
            }
        });

        formatLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        formatLabel.setText("(yyyy-MM-dd)");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(newButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nationLabel)
                            .addComponent(genderLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(birthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(firstInput)
                            .addComponent(lastInput)
                            .addComponent(genderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nationBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthInput))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(kolofonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(kolofonLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton)
                    .addComponent(newButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLabel)
                    .addComponent(formatLabel))
                .addGap(9, 9, 9)
                .addComponent(birthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(resetButton))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        if (newButton.isSelected())
        {
            createButton.setEnabled(true);
            registerButton.setSelected(false);
            resetButton.setEnabled(false);
            
            enableLabel();
            labelVisible();
            
        }
    }//GEN-LAST:event_newButtonActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        
    }//GEN-LAST:event_genderBoxActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String name;
        
        collect();
     
        addToArrayList();
        
        panelPopUp();
        
        //dateFormat();
    }//GEN-LAST:event_createButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
      reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
       
        if (registerButton.isSelected())
        {
            resetButton.setEnabled(true);
            newButton.setSelected(false);
            createButton.setEnabled(false);
            labelUnvisible();
            profileLabel.setVisible(true);
            profileLabel.setText(athleteOne.get(0) + " " + athleteOne.get(1));
         
        }
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void lastInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastInputActionPerformed

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
       //new FormathleteOne(athleteOne).setVisible(true);
       
       //String a;
       //athleteOne = a;
       String One = String.join(" ,", athleteOne);
       FormAthleteOne form = new FormAthleteOne(One);
       
       name = athleteOne.get(0) + " " + athleteOne.get(1);
       genders = athleteOne.get(2);
       Dob = athleteOne.get(3);
       country = athleteOne.get(4);
       
       //dataTrans();
       
       //systemTest();
       
       
       this.setVisible(false);
       new FormAthleteOne().setVisible(false);
       new FormAthleteOne(One).setVisible(true);
      
    }//GEN-LAST:event_profileLabelMouseClicked

    private void birthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthInputActionPerformed
        
    }//GEN-LAST:event_birthInputActionPerformed

    private void labelUnvisible()
    {
        firstLabel.setVisible(false);
        firstInput.setVisible(false);
        lastLabel.setVisible(false);
        lastInput.setVisible(false);
        genderLabel.setVisible(false);
        genderBox.setVisible(false);
        birthLabel.setVisible(false);
        birthInput.setVisible(false);
        nationLabel.setVisible(false);
        nationBox.setVisible(false);
        formatLabel.setVisible(false);
        
    }
    
    private void labelVisible()
    {
        firstLabel.setVisible(true);
        firstInput.setVisible(true);
        lastLabel.setVisible(true);
        lastInput.setVisible(true);
        genderLabel.setVisible(true);
        genderBox.setVisible(true);
        birthLabel.setVisible(true);
        birthInput.setVisible(true);
        nationLabel.setVisible(true);
        nationBox.setVisible(true);
    }
    private void addToArrayList()
    {   
        
        athleteOne.add(firstName.get(0));
        athleteOne.add(lastName.get(0));
        athleteOne.add(gender.get(0));
        athleteOne.add(birthDate.get(0));
        athleteOne.add(nationality.get(0));
        
        //System.out.println(athleteOne);
    }
    
//    private void dataTrans()
//    {
//        FormAthleteOne form = new FormAthleteOne(name);
//        FormAthleteOne form = new FormAthleteOne(genders);
//        FormAthleteOne form = new FormAthleteOne(Dob);
//    }
    
    private void systemTest()
    {
        System.out.println(name);
        System.out.println(genders);
        System.out.println(Dob);
        System.out.println(country);
    }
    
  
//    private void addToAthlete()
//    {
//        athlete.add(firstName);
//        athlete.add(lastName);
//        athlete.add(gender);
//        athlete.add(birthDate);
//        athlete.add(nationality);
//        
//        System.out.println(athlete);
//    }
    
//    private void outprint()
//    {
//        System.out.println(firstName);
//        System.out.println(lastName);
//        System.out.println(gender);
//        System.out.println(birthDate);
//        System.out.println(nationality);
//    }
    
    private void disableLabel()
    {
         //Disable all the labels and input before the user choosing their perpose.(new or registered)
        firstLabel.setEnabled(false);
        firstInput.setEnabled(false);
        lastLabel.setEnabled(false);
        lastInput.setEnabled(false);
        genderLabel.setEnabled(false);
        genderBox.setEnabled(false);
        birthLabel.setEnabled(false);
        birthInput.setEnabled(false);
        nationLabel.setEnabled(false);
        nationBox.setEnabled(false);
        formatLabel.setEnabled(false);
    }
    
    private void enableLabel()
    {
            //enable all the label and input for user after they choose on new register.
            firstLabel.setEnabled(true);
            firstInput.setEnabled(true);
            lastLabel.setEnabled(true);
            lastInput.setEnabled(true);
            genderLabel.setEnabled(true);
            genderBox.setEnabled(true);
            birthLabel.setEnabled(true);
            birthInput.setEnabled(true);
            nationLabel.setEnabled(true);
            nationBox.setEnabled(true);
            formatLabel.setEnabled(true);
    }
    
    private void collect()
    {
        firstName.add(firstInput.getText());
        lastName.add(lastInput.getText());
        gender.add((String)genderBox.getSelectedItem());
        birthDate.add(birthInput.getText());
        nationality.add((String)nationBox.getSelectedItem());
    }
    
    private void panelPopUp()
    {
        f1 = firstInput.getText();
        l2 = lastInput.getText();
        g3 = (String)genderBox.getSelectedItem();
        b4 = birthInput.getText();
        n5 = (String)nationBox.getSelectedItem();

        JFrame frame = new JFrame("Message");
        if (f1.isEmpty() || l2.isEmpty() || g3.equals("Select Your Gender") || b4.isEmpty() ||n5.equals("Select Your Nationality"))
        {
           failPane.showMessageDialog(frame,"Please Try Again!");
        }
        else
        {
            successPane.showMessageDialog(frame,"You have successfully created a profile!");
            resetButton.setEnabled(true);
        }
    }
    
   
//    private void dateFormat()
//    {
//        String d;
//        d = birthInput.getText();
//        birthInput.setText(s.format(d));
//        
//        System.out.println(d);
//    }
    
    private void reset()
    {
        firstInput.setText(null);
        lastInput.setText(null);
        genderBox.setSelectedIndex(0);
        birthInput.setText(null);
        nationBox.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKolofon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKolofon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKolofon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKolofon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKolofon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthInput;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JOptionPane failPane;
    private javax.swing.JTextField firstInput;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JComboBox genderBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel kolofonLabel;
    private javax.swing.JTextField lastInput;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JComboBox nationBox;
    private javax.swing.JLabel nationLabel;
    private javax.swing.JRadioButton newButton;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JRadioButton registerButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JOptionPane successPane;
    // End of variables declaration//GEN-END:variables
}
