/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shhua8751
 */

import java.util.*;
import javax.swing.JFrame;
public class FormAthleteOne extends javax.swing.JFrame {
        String a;
        ArrayList <String> info = new ArrayList();
        
        //eventsArrayList
        ArrayList <String> tripleJump    = new ArrayList();
        ArrayList <String> longJump      = new ArrayList();
        ArrayList <String> hurdles       = new ArrayList();
        ArrayList <String> one           = new ArrayList();
        ArrayList <String> two           = new ArrayList();
        ArrayList <String> four          = new ArrayList();
        ArrayList <String> eight         = new ArrayList();
        ArrayList <String> fifteen       = new ArrayList();
        ArrayList <String> thirty        = new ArrayList();
        ArrayList <String> highJump      = new ArrayList();
        ArrayList <String> shotPut       = new ArrayList();
        ArrayList <String> javelin       = new ArrayList();
        ArrayList <String> poleVault     = new ArrayList();
        

        
        //String components for the info
        String first;
        String last;
        String name;
        String gender;
        String date;
        String country;
        
        //String event for future code
        String event;
        
        
        
        
                
        
        
    /**
     * Creates new form athleteOne
     */
    public FormAthleteOne(String para)
    {
        initComponents();
        //System.out.println(para);
        
        //Unable displayButton
        displayButton.setEnabled(false);
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
        
        event = (String)eventBox.getSelectedItem();

        a = para;
        
        spilt();
        
        addToArrayList();
        
        labelText();
        
        //strsTest();
       
        //System.out.println(info.get(0));
    }
    public FormAthleteOne() {
        initComponents(); 
        //addToArrayList();
        //System.out.println(info);
        
        //labelText();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        vaildPane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameOutput = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderOutput = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateOutput = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        countryOutput = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        eventBox = new javax.swing.JComboBox<String>();
        addButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resultInput = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        displayButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Athlete Profile");

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Athlete Profile");

        nameLabel.setText("Athlete Name:");

        nameOutput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        genderLabel.setText("Gender:");

        genderOutput.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N

        dateLabel.setText("Date of Birth:");

        dateOutput.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N

        countryLabel.setText("Nationality:");

        countryOutput.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("Y:\\Documents\\Life-profile-pics-latest.png")); // NOI18N

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        eventBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Event", "100M", "110M Hurdles", "200M", "400M", "800M", "1500M", "3000M", "Long Jump", "Triple Jump", "High Jump", "Pole Vault", "Shot Put", "Javelin" }));
        eventBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBoxActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resultInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultInputActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        hintLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        hintLabel.setText("Results    (6 spaces)    Date");

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryLabel)
                            .addComponent(countryOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel)
                            .addComponent(nameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(resultInput, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(countryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(resultInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayButton)
                            .addComponent(backButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       this.setVisible(false);
       new FormKolofon().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void eventBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       addResult();
       resultInput.setText(null);
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
      
      
      JFrame frame = new JFrame("Message");
       displayButton.setEnabled(true);
          addButton.setEnabled(true);
          removeButton.setEnabled(true);
      
//      if (event == "Select Your Event")
//      {
//          vaildPane.showMessageDialog(frame, "Invaild Event!\n" + "Please Try again!");
//      }
//      else
//      {
//          displayButton.setEnabled(true);
//          addButton.setEnabled(true);
//          removeButton.setEnabled(true);
//      }
//      
      
      
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resultInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultInputActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       removeSize();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        displayResult();
    }//GEN-LAST:event_displayButtonActionPerformed
        
    private void spilt()
    {
        String[] buff = a.split(",");
//        for(int i=0;i<buff.length;i++)
//        {
//            //System.out.println(buff[i]);
//        }
        //buff.toString();
        first   = buff[0];
        last    = buff[1];
        gender  = buff[2];
        date    = buff[3];
        country = buff[4];
       
        
        
        //strsTest();
                
        
        
    }
    
    
    private void addToArrayList()
    {
        info.add(first);
        info.add(last);
        info.add(gender);
        info.add(date);
        info.add(country);
        System.out.println(info);
    }
    
    private void labelText()
    {
//        name    = first + " " +last;
//        
//        nameOutput.setText(name);
//        genderOutput.setText(gender);
//        dateOutput.setText(date);
//        countryOutput.setText(country);
        //System.out.println(info);
        
        nameOutput.setText(info.get(0) + " " + info.get(1));
        genderOutput.setText(info.get(2));
        dateOutput.setText(info.get(3));
        countryOutput.setText(info.get(4));
        
       
    }
    
    private void strsTest()
    {
        System.out.println(first);
        System.out.println(last);
        System.out.println(gender);
        System.out.println(date);
        System.out.println(country);
        System.out.println(name);
    }
    
    private void addResult()
    {
         event = (String) eventBox.getSelectedItem();
        
        if (event == "100M")
        {
            one.add(resultInput.getText());
            System.out.println(one);
        }
        else if (event == "200M")
        {
            two.add(resultInput.getText());
        }
        else if (event == "400M")
        {
            four.add(resultInput.getText());
        }
        else if (event == "800M")
        {
            eight.add(resultInput.getText());
        }
        else if (event == "1500M")
        {
            fifteen.add(resultInput.getText());
        }
        else if (event == "3000M")
        {
            thirty.add(resultInput.getText());
        }
        else if (event == "110M Hurdles")
        {
            hurdles.add(resultInput.getText());
        }
        else if (event == "Long Jump")
        {
            longJump.add(resultInput.getText());
        }
        else if (event == "Triple Jump")
        {
            tripleJump.add(resultInput.getText());
        }
        else if (event == "High Jump")
        {
            highJump.add(resultInput.getText());
        }
        else if (event == "Pole Vault")
        {
            poleVault.add(resultInput.getText());
        }
        else if (event == "Shot Put")
        {
            shotPut.add(resultInput.getText());
        }
        else if (event == "Javelin")
        {
            javelin.add(resultInput.getText());
        }
    }
    
    private void removeSize()
    {
         event = (String) eventBox.getSelectedItem();
        
        if (event == "100M")
        {
            one.remove(one.size()-1);
        }
        else if (event == "200M")
        {
            two.remove(two.size()-1);
        }
        else if (event == "400M")
        {
            four.remove(four.size()-1);
        }
        else if (event == "800M")
        {
            eight.remove(eight.size()-1);
        }
        else if (event == "1500M")
        {
            fifteen.remove(fifteen.size()-1);
        }
        else if (event == "3000M")
        {
            thirty.remove(thirty.size()-1);
        }
        else if (event == "110M Hurdles")
        {
            hurdles.remove(hurdles.size()-1);
        }
        else if (event == "Long Jump")
        {
            longJump.remove(longJump.size()-1);
        }
        else if (event == "Triple Jump")
        {
            tripleJump.remove(tripleJump.size()-1);
        }
        else if (event == "High Jump")
        {
            highJump.remove(highJump.size()-1);
        }
        else if (event == "Pole Vault")
        {
            poleVault.remove(poleVault.size()-1);
        }
        else if (event == "Shot Put")
        {
            shotPut.remove(shotPut.size()-1);
        }
        else if (event == "Javelin")
        {
            javelin.remove(javelin.size()-1);
        }
    }
    
    private void displayResult()
    {
        event = (String) eventBox.getSelectedItem();
        
        display.setText(event + "Result:\n");
        
        if (event == "100M")
        {
            for (int i = 0; i < one.size(); i++)
            {
                display.append(one.get(i) + "\n");
            }
        }
        else if (event == "200M")
        {
            for (int i = 0; i < two.size(); i++)
            {
                display.append( two.get(i) + "\n");
            }
        }
        else if (event == "400M")
        {
            for (int i = 0; i < four.size(); i++)
            {
                display.append( four.get(i) + "\n");
            }
        }
        else if (event == "800M")
        {
            for (int i = 0; i < eight.size(); i++)
            {
                display.append( eight.get(i) + "\n");
            }
        }
        else if (event == "1500M")
        {
            for (int i = 0; i < fifteen.size(); i++)
            {
                display.append( fifteen.get(i) + "\n");
            }
        }
        else if (event == "3000M")
        {
            for (int i = 0; i < thirty.size(); i++)
            {
                display.append( thirty.get(i) + "\n");
            }
        }
        else if (event == "110M Hurdles")
        {
            for (int i = 0; i < hurdles.size(); i++)
            {
                display.append( hurdles.get(i) + "\n");
            }
        }
        else if (event == "Long Jump")
        {
            for (int i = 0; i < longJump.size(); i++)
            {
                display.append( longJump.get(i) + "\n");
            }
        }
        else if (event == "Triple Jump")
        {
            for (int i = 0; i < tripleJump.size(); i++)
            {
                display.append( tripleJump.get(i) + "\n");
            }
        }
        else if (event == "High Jump")
        {
            for (int i = 0; i < highJump.size(); i++)
            {
                display.append( highJump.get(i) + "\n");
            }
        }
        else if (event == "Pole Vault")
        {
            for (int i = 0; i < poleVault.size(); i++)
            {
                display.append( poleVault.get(i) + "\n");
            }
        }
        else if (event == "Shot Put")
        {
            for (int i = 0; i < shotPut.size(); i++)
            {
                display.append( shotPut.get(i) + "\n");
            }
        }
        else if (event == "Javelin")
        {
            for (int i = 0; i < javelin.size(); i++)
            {
                display.append( javelin.get(i) + "\n");
            }
        }
    }
    
//    private void addToArrayList(String [] args)
//    {
//        info.add(buff)；
//    }
//    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAthleteOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAthleteOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAthleteOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAthleteOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAthleteOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel countryOutput;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateOutput;
    private javax.swing.JTextArea display;
    private javax.swing.JButton displayButton;
    private javax.swing.JComboBox<String> eventBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderOutput;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameOutput;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField resultInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JOptionPane vaildPane;
    // End of variables declaration//GEN-END:variables
}
